# NumPy Exercises — 50 Problems

**Instructions:**
- Run the first cell to import NumPy before starting.
- Each exercise has a **Question** and an **Input** (where given).
- Write your solution in the `# Write your code here:` cell below each question.
- Run your cell to check your output.
- Do **not** modify the Input cells or the import cell.

> **Tip:** Use `Shift + Enter` to run a cell and move to the next one.

## Setup

In [3]:
# Run this cell before starting — do not modify
import numpy as np

## Section 1 — Array Basics (Exercises 1–10)

### Exercise 1 — NumPy Version

**Question:** Print the version of NumPy.


In [2]:
# Write your code here:
print(np.__version__)

2.0.2


### Exercise 2 — 1D Array

**Question:** Create a 1D array of numbers from 0 to 9.


In [8]:
# Write your code here:
array = np.array([0,1,2,3,4,5,6,7,8,9])
print(array)

[0 1 2 3 4 5 6 7 8 9]


### Exercise 3 — Boolean Array

**Question:** Create a 3×3 NumPy array of all `True`s.


In [9]:
# Write your code here:
boolean_arr = np.full((3,3), True)
print(boolean_arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Exercise 4 — Filter Odd Numbers

**Question:** Extract all odd numbers from `arr`.


In [5]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Write your code here:
for x in arr:
  if(x%2!=0): print(x)

1
3
5
7
9


### Exercise 5 — Replace In-Place

**Question:** Replace all odd numbers in `arr` with `-1`.


In [21]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# Write your code here:
for i in range(len(arr)):
  if(arr[i]%2!=0): arr[i] = -1

print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 6 — Replace Without Modifying Original

**Question:** Replace all odd numbers in `arr` with `-1` **without** changing the original array.


In [23]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Write your code here:


### Exercise 7 — Reshape Array

**Question:** Convert a 1D array to a 2D array with 2 rows.


In [24]:
# Input — do not modify
arr = np.arange(10)

In [28]:
# Write your code here:
arr2D = arr.reshape(2,-1)
print(arr2D)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Exercise 8 — Vertical Stack

**Question:** Stack arrays `a` and `b` vertically.


In [31]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [32]:
# Write your code here:
vertical = np.vstack((a,b))
print(vertical)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Exercise 9 — Horizontal Stack

**Question:** Stack arrays `a` and `b` horizontally.


In [33]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [34]:
# Write your code here:
horizontal = np.hstack((a,b))
print(horizontal)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### Exercise 10 — Custom Sequence

**Question:** Create the following pattern **without hardcoding**. Use only NumPy functions and the input array `a`.

Expected output: `array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`


In [46]:
# Input — do not modify
a = np.array([1, 2, 3])

In [56]:
# Write your code here:
matrix = np.vstack((np.vstack((a,a)),a))
matrix = matrix.T
matrix = matrix.reshape(-1)
matrix = np.hstack((matrix,a))
matrix = np.hstack((matrix,a))
matrix = np.hstack((matrix,a))
print(matrix)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


## Section 2 — Set Operations & Filtering (Exercises 11–19)

### Exercise 11 — Common Items

**Question:** Get the common items between arrays `a` and `b`.


In [64]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [67]:
# Write your code here:
common_items = np.intersect1d(a, b)
print(common_items)


[2 4]


### Exercise 12 — Remove Items

**Question:** From array `a`, remove all items present in array `b`.


In [68]:
# Input — do not modify
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [69]:
# Write your code here:
common = np.intersect1d(a,b)
for x in common:
  a = a[a!=x]
print(a)

[1 2 3 4]


### Exercise 13 — Matching Positions

**Question:** Get the positions where elements of `a` and `b` match.


In [71]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [72]:
# Write your code here:
for i in range(len(a)):
  if(a[i]==b[i]): print(i)

1
3
5
7


### Exercise 14 — Extract Range

**Question:** Get all items between 5 and 10 from array `a`.


In [76]:
# Input — do not modify
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [80]:
# Write your code here:
a = a[(a>=5) & (a<=10)]
print(a)



[ 6  9 10]


### Exercise 15 — Vectorize a Function

**Question:** Convert the scalar function `maxx` below to work on two arrays.


In [81]:
# Input — do not modify
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [82]:
# Write your code here:
def maxx_arr(x,y):
  for a in range(len(x)):
    if(x[a]>=y[a]): x[a] = x[a]
    else: x[a] = y[a]
  return x

print(maxx_arr(a,b))

[6 7 9 8 9 7 5]


### Exercise 16 — Swap Columns

**Question:** Swap columns 1 and 2 in array `arr`.


In [89]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [90]:
# Write your code here:
arr[:, [0,1]] = arr[:, [1,0]]
print(arr)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


### Exercise 17 — Swap Rows

**Question:** Swap rows 1 and 2 in array `arr`.


In [96]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [97]:
# Write your code here:
arr[[0,1]] = arr[[1,0]]
print(arr)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


### Exercise 18 — Reverse Rows

**Question:** Reverse the rows of the 2D array `arr`.


In [109]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [110]:
# Write your code here:
arr = np.flip(arr, axis=1)
print(arr)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


### Exercise 19 — Reverse Columns

**Question:** Reverse the columns of the 2D array `arr`.


In [111]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [112]:
# Write your code here:
arr = np.flip(arr, axis=0)
print(arr)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


## Section 3 — Printing & Formatting (Exercises 20–24)

### Exercise 20 — Random Float Array

**Question:** Create a 2D array of shape 5×3 containing random decimal numbers between 5 and 10.


In [4]:
# Write your code here:
arr_random = np.random.uniform(5,10, size=(5,3))
print(arr_random)

[[9.63009096 5.33518287 9.67082038]
 [8.98160628 6.17836312 9.05376427]
 [8.64972814 7.17529332 9.45490692]
 [8.50710392 7.0793611  9.74426908]
 [9.71807715 8.1208622  8.77654006]]


### Exercise 21 — Decimal Places

**Question:** Print only 3 decimal places of the array `rand_arr`.


In [6]:
# Input — do not modify
rand_arr = np.random.random((5,3))

In [7]:
# Write your code here:
print(np.around(rand_arr, decimals=3))

[[0.354 0.826 0.063]
 [0.645 0.233 0.187]
 [0.834 0.371 0.589]
 [0.177 0.976 0.72 ]
 [0.078 0.872 0.391]]


### Exercise 22 — Suppress Scientific Notation

**Question:** Pretty print `rand_arr` by suppressing scientific notation (like `1e10`).


In [8]:
# Input — do not modify
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

In [ ]:
# Write your code here:


### Exercise 23 — Limit Print Output

**Question:** Limit the number of items printed in array `a` to a maximum of 6 elements.


In [19]:
# Input — do not modify
a = np.arange(15)

In [20]:
# Write your code here:
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ... 12 13 14]


### Exercise 24 — Print Full Array

**Question:** Print the full NumPy array `a` without truncating.


In [32]:
# Input — do not modify
np.set_printoptions(threshold=6)
a = np.arange(15)

In [33]:
# Write your code here:
import sys
with np.printoptions(threshold=sys.maxsize):
  print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Section 4 — Iris Dataset (Exercises 25–46)

### Exercise 25 — Import Dataset

**Question:** Import the Iris dataset keeping the text intact.

> URL: `https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv`


In [35]:
# Write your code here:
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'
iris_data = np.genfromtxt(url, delimiter=',', dtype='str')
print(iris_data)

[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ...
 ['6.5' '3.0' '5.2' '2.0' 'Iris-virginica']
 ['6.2' '3.4' '5.4' '2.3' 'Iris-virginica']
 ['5.9' '3.0' '5.1' '1.8' 'Iris-virginica']]


### Exercise 26 — Extract Text Column

**Question:** Extract the text column `species` from the 1D iris dataset imported in Exercise 25.

*# Make sure you have run Exercise 25 first so that iris_data is defined.*


In [38]:
# Write your code here:
with np.printoptions(threshold=sys.maxsize):
     print(iris_data[:,4])

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

### Exercise 27 — 1D to 2D Array

**Question:** Convert the 1D iris dataset to a 2D array `iris_2d` by omitting the species text field.

*# Make sure you have run Exercise 25 first.*


In [39]:
# Write your code here:
iris_data_notxt = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris_data_notxt.reshape(2,-1))

[[5.1 3.5 1.4 ... 2.9 4.3 1.3]
 [6.6 3.  4.4 ... 3.  5.1 1.8]]


### Exercise 28 — Mean, Median, Std

**Question:** Find the mean, median, and standard deviation of the sepal length (1st column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:


### Exercise 29 — Normalize Array

**Question:** Create a normalized form of iris's sepal length whose values range exactly between 0 and 1 (minimum → 0, maximum → 1).

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:


### Exercise 30 — Softmax Score

**Question:** Compute the softmax score of the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:


### Exercise 31 — Percentile Scores

**Question:** Find the 5th and 95th percentile of iris's sepal length.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:


### Exercise 32 — Insert Missing Values

**Question:** Insert `np.nan` values at 20 random positions in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:


### Exercise 33 — Find Missing Values

**Question:** Find the **number** and **position** of missing values in `iris_2d`'s sepal length (1st column).

*# Make sure you have run Exercise 32 first.*


In [ ]:
# Write your code here:


### Exercise 34 — Multi-Condition Filter

**Question:** Filter the rows of `iris_2d` that have:
- petal length (3rd column) > 1.5, **and**
- sepal length (1st column) < 5.0

*# Make sure you have run Exercise 32 first.*


In [ ]:
# Write your code here:


### Exercise 35 — Drop Rows with NaN

**Question:** Select rows of `iris_2d` that do **not** have any `nan` value.

*# Make sure you have run Exercise 32 first.*


In [ ]:
# Write your code here:


### Exercise 36 — Correlation

**Question:** Find the correlation between sepal length (1st column) and petal length (3rd column) in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:


### Exercise 37 — Check for NaN

**Question:** Find out if `iris_2d` has any missing values.

*# Make sure you have run Exercise 32 first.*


In [ ]:
# Write your code here:


### Exercise 38 — Replace NaN with 0

**Question:** Replace all occurrences of `nan` with `0` in `iris_2d`.

*# Make sure you have run Exercise 32 first.*


In [ ]:
# Write your code here:


### Exercise 39 — Unique Value Counts

**Question:** Find the unique values and their counts in iris's species column.

*# Make sure you have run Exercise 25 first.*


In [ ]:
# Write your code here:


### Exercise 40 — Numeric to Categorical

**Question:** Bin the petal length (3rd column) of `iris_2d` to form a text array using these rules:
- `< 3` → `'small'`
- `3–5` → `'medium'`
- `>= 5` → `'large'`

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:


### Exercise 41 — Create New Column

**Question:** Create a new column for **volume** in `iris_2d`, where:

> volume = (π × petal_length × sepal_length²) / 3

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:


### Exercise 42 — Probabilistic Sampling

**Question:** Randomly sample iris's species such that **setosa** appears **twice** as often as versicolor and virginica.

*# Make sure you have run Exercise 25 first.*


In [ ]:
# Write your code here:


### Exercise 43 — Second Largest Value

**Question:** Find the **second longest** petal length among iris samples of species **setosa**.

*# Make sure you have run Exercise 25 first.*


In [ ]:
# Write your code here:


### Exercise 44 — Sort 2D Array by Column

**Question:** Sort the iris dataset based on the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:


### Exercise 45 — Most Frequent Value

**Question:** Find the most frequent value of petal length (3rd column) in the iris dataset.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:


### Exercise 46 — First Value Greater Than

**Question:** Find the position of the **first occurrence** of a value greater than 1.0 in the petal width (4th column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:


## Section 5 — Miscellaneous (Exercises 47–50)

### Exercise 47 — Clip Values

**Question:** From array `a`, replace all values **greater than 30** with `30`, and all values **less than 10** with `10`.


In [ ]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [ ]:
# Write your code here:


### Exercise 48 — Top N Positions

**Question:** Get the positions of the **top 5 maximum values** in array `a`.


In [ ]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [ ]:
# Write your code here:


### Exercise 49 — Row-wise Unique Counts

**Question:** Compute the counts of unique values **row-wise** in the input array.


In [ ]:
# Input — do not modify
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))

In [ ]:
# Write your code here:


### Exercise 50 — Flatten Array of Arrays

**Question:** Convert `arr_2d` (an array of arrays) into a flat 1D array.


In [ ]:
# Input — do not modify
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)
arr_2d = np.array([arr1, arr2, arr3], dtype=object)

In [ ]:
# Write your code here:


---

## 🎉 Well done!

You've completed all 50 exercises. Review any exercises you found tricky and revisit the NumPy documentation for deeper understanding.